nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Peltzer, Alexander & Mohr, Christopher
  description: A Nanostring nCounter analysis pipeline
  force: false
  is_nfcore: true
  name: nanostring
  org: nf-core
  outdir: .
  version: 1.4.0dev
